DROP TABLE IF EXISTS "JoinRequest";
DROP TABLE IF EXISTS "Member";
DROP TABLE IF EXISTS "Participant";
DROP TABLE IF EXISTS "Event";
DROP TABLE IF EXISTS "GroupCategories";
DROP TABLE IF EXISTS "UserInterests";
DROP TABLE IF EXISTS "Group";
DROP TABLE IF EXISTS "Category";
DROP TABLE IF EXISTS "User";

DROP TYPE IF EXISTS "JoinRequestStatus";
DROP TYPE IF EXISTS "MemberRole";
