ALTER TABLE "Event" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Group" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Category" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Member" ALTER COLUMN "id" DROP DEFAULT;
