// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserInterest = `-- name: AddUserInterest :one
INSERT INTO "UserInterests"("user_id", "interest_id")
VALUES ($1, $2)
RETURNING user_id, interest_id
`

type AddUserInterestParams struct {
	UserID     uuid.UUID
	InterestID uuid.UUID
}

func (q *Queries) AddUserInterest(ctx context.Context, arg AddUserInterestParams) (UserInterest, error) {
	row := q.db.QueryRow(ctx, addUserInterest, arg.UserID, arg.InterestID)
	var i UserInterest
	err := row.Scan(&i.UserID, &i.InterestID)
	return i, err
}

const changeUserName = `-- name: ChangeUserName :one
UPDATE "User"
SET "name" = $2
WHERE "id" = $1
RETURNING id, name, profile_pic
`

type ChangeUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ChangeUserName(ctx context.Context, arg ChangeUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, changeUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.ProfilePic)
	return i, err
}

const changeUserProfilePic = `-- name: ChangeUserProfilePic :one
UPDATE "User"
SET "profile_pic" = $2
WHERE "id" = $1
RETURNING id, name, profile_pic
`

type ChangeUserProfilePicParams struct {
	ID         uuid.UUID
	ProfilePic pgtype.Text
}

func (q *Queries) ChangeUserProfilePic(ctx context.Context, arg ChangeUserProfilePicParams) (User, error) {
	row := q.db.QueryRow(ctx, changeUserProfilePic, arg.ID, arg.ProfilePic)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.ProfilePic)
	return i, err
}

const changeUserProperties = `-- name: ChangeUserProperties :one
UPDATE "User"
SET "name" = $2,
    "profile_pic" = $3
WHERE "id" = $1
RETURNING id, name, profile_pic
`

type ChangeUserPropertiesParams struct {
	ID         uuid.UUID
	Name       string
	ProfilePic pgtype.Text
}

func (q *Queries) ChangeUserProperties(ctx context.Context, arg ChangeUserPropertiesParams) (User, error) {
	row := q.db.QueryRow(ctx, changeUserProperties, arg.ID, arg.Name, arg.ProfilePic)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.ProfilePic)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "User" ("id", "name", "profile_pic")
VALUES ($1, $2, $3)
RETURNING id, name, profile_pic
`

type CreateUserParams struct {
	ID         uuid.UUID
	Name       string
	ProfilePic pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Name, arg.ProfilePic)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.ProfilePic)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, profile_pic
FROM "User"
WHERE "id" = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.ProfilePic)
	return i, err
}

const getUserInterests = `-- name: GetUserInterests :many
SELECT c.id, c.category, c.created_at, c.updated_at, c.deleted_at
FROM "UserInterests" as ui
  JOIN "Category" as c
  ON ui.interest_id = c.id
WHERE ui.user_id = $1
  AND c.deleted_at IS NULL
`

func (q *Queries) GetUserInterests(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getUserInterests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserInterest = `-- name: RemoveUserInterest :exec
DELETE FROM "UserInterests"
WHERE "user_id" = $1
  AND "interest_id" = $2
`

type RemoveUserInterestParams struct {
	UserID     uuid.UUID
	InterestID uuid.UUID
}

func (q *Queries) RemoveUserInterest(ctx context.Context, arg RemoveUserInterestParams) error {
	_, err := q.db.Exec(ctx, removeUserInterest, arg.UserID, arg.InterestID)
	return err
}
