// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Group struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ProfilePic  string `json:"profile_pic"`
	IsVerified  bool   `json:"isVerified"`
	IsOpen      bool   `json:"isOpen"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Mutation struct {
}

type NewGroup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ProfilePic  string `json:"profile_pic"`
	IsOpen      bool   `json:"isOpen"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
